### ISSUE TITLE
Cierre Milestone 0

### ISSUE THREAD

**Issue by RubenDelgadoPareja** [RubenDelgadoPareja/TFG-Triage-Inteligente-Consulta-Medica#64]
Al cerrar esta issue debemos tener un PVM con todo lo realizado en la Milestone 0 : 

- [x] Comprobadores de la ortografía y gramática de la documentación
- [x] Comprobadores de compilación de LaTeX
- [x] Establecer los Milestones
- [x] Establecer las Historias de Usuario y reflejarlas en la documentación
- [x] Establecer los clientes del producto mediante User Journeys.
- [x] Completar en la documentación los apartados de Motivación , Objetivos y Metodología
- [x] Montar la infraestructura primitiva del proyecto y añadir ESLinter + Prettier
- [x] Integración Continua: Construir la memoria y ejecutar sus comprobadores ortográficos
- [x] Integración Continua: Correr el ESLinter para asegurar la calidad en el código
